image: mdunhem/docker-angular-jenkins:1.1.2

## Hack for now to get this to work
variables:
  GIT_SSL_NO_VERIFY: "true"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: "$CI_COMMIT_REF_NAME"
  untracked: true

stages:
  - install
  - test
  - build
  - deploy

install:
  stage: install
  script:
    - npm install

lint:
  stage: test
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test

build:
  stage: build
  script:
    - npm run build:prod

deploy:
  stage: deploy
  image: docker:latest
  services:
     - docker:dind
  only:
    - tags
  script:
    - apk add --update py-pip && pip install docker-compose
    - docker-compose build
    - docker-compose up -d
  environment:
    name: production
    url: http://411greenf17.cs.odu.edu
